user nginx;
worker_processes auto;
events { worker_connections 1024; }
stream {
    upstream wazuh_managers {
        server wazuh-manager-local:1514;
    }
    server {
        listen 1514;
        proxy_pass wazuh_managers;
        proxy_timeout 10m;
        proxy_connect_timeout 30s;
    }
}
